name: Lint

on: [push, pull_request]

jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Lint
        uses: py-actions/flake8@v2
        with:
          path: "specs_micro"
          ignore: "F401,F403,W292,E402"
          max-line-length: "120"
